// Guess the Year: well-known facts/events paired with the year they happened.
// Scoring rewards the closest guess (see room.js's pollguess-style podium logic).
module.exports = [
  { text: "The first iPhone is released.", year: 2007 },
  { text: "The Berlin Wall falls.", year: 1989 },
  { text: "Humans land on the Moon for the first time.", year: 1969 },
  { text: "The World Wide Web is made publicly available.", year: 1991 },
  { text: "Titanic sinks on its maiden voyage.", year: 1912 },
  { text: "Facebook opens to the general public.", year: 2006 },
  { text: "The first Star Wars film premieres.", year: 1977 },
  { text: "The Great Fire of London destroys most of the city.", year: 1666 },
  { text: "Netflix is founded (as a DVD-by-mail company).", year: 1997 },
  { text: "The Wright brothers achieve the first powered flight.", year: 1903 },
  { text: "The Soviet Union is officially dissolved.", year: 1991 },
  { text: "YouTube is founded.", year: 2005 },
  { text: "The first modern Olympic Games are held in Athens.", year: 1896 },
  { text: "The Simpsons first airs as a full episode series.", year: 1989 },
  { text: "The Chernobyl nuclear disaster occurs.", year: 1986 },
  { text: "Pluto is reclassified as a dwarf planet.", year: 2006 },
  { text: "The first PlayStation console is released.", year: 1994 },
  { text: "Nelson Mandela is released from prison.", year: 1990 },
  { text: "The Human Genome Project is completed.", year: 2003 },
  { text: "Amazon.com opens as an online bookstore.", year: 1995 },
  { text: "The Beatles release their first single, \"Love Me Do.\"", year: 1962 },
  { text: "The first text message (SMS) is sent.", year: 1992 },
  { text: "Dolly the sheep, the first cloned mammal, is born.", year: 1996 },
  { text: "The Eiffel Tower is completed.", year: 1889 },
  { text: "World War II ends.", year: 1945 },
  { text: "The first Harry Potter book is published.", year: 1997 },
  { text: "Google is founded.", year: 1998 },
  { text: "The Panama Canal officially opens.", year: 1914 },
  { text: "The first successful heart transplant is performed.", year: 1967 },
  { text: "Instagram is launched.", year: 2010 }
];
